apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: twingate-operator
    repoURL: ghcr.io/twingate/helmcharts
    targetRevision: "*"
    helm:
      valuesObject:
        twingateOperator:
          network: nethworks
          remoteNetworkName: "argocd-k8s-operator"
          existingAPIKeySecret:
            name: twingate-operator-api-token
            key: TWINGATE_API_KEY
        kubernetes-access-gateway:
          enabled: true  # Enable Gateway subchart
          twingate:
            network: nethworks
            resource:
              # Annotate Gateway service as a Twingate resource
              enabled: true
              extraAnnotations:
                resource.twingate.com/name: "argocd-k8s-gateway"
                resource.twingate.com/alias: "neth-gcp-argo.int"
  destination:
    server: https://kubernetes.default.svc
    namespace: twingate-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true