apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate-connectors
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/neth-tg/gcp-gitops.git
    targetRevision: main
    path: base/twingate-connectors
  destination:
    server: https://kubernetes.default.svc
    namespace: twingate-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true